import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,copyFile,writeFile,readFile,rm,mkdir} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {spawn} from 'node:child_process';import {createServer} from 'node:http';
import {setup,fixture} from './fixtures.mjs';import {nodeServer} from '../src/server.mjs';
import {canonical,hash,seal,hashBytes} from '../src/canonical.mjs';import {STANDING_CAPABILITY} from '../src/need.mjs';import {RESOLUTION_PATH,CAPABILITY_CLASS} from '../src/protocol.mjs';
const clock=()=>Math.floor(Date.now()/1000),E='evidence/public-v1/cold';
async function cold(bytes){const d=await mkdtemp(join(tmpdir(),'clean-agent-'));try{
  await copyFile(new URL('../scripts/cold-agent.py',import.meta.url),join(d,'reader.py'));await writeFile(join(d,'only-input.json'),bytes);
  const env={PATH:process.env.PATH,HOME:d,TMPDIR:tmpdir(),PYTHONDONTWRITEBYTECODE:'1'};
  return await new Promise((resolve,reject)=>{const c=spawn('python3',['-I',join(d,'reader.py'),join(d,'only-input.json')],{cwd:d,env});let stdout='',stderr='';const timer=setTimeout(()=>{c.kill('SIGKILL');reject(Error('COLD_PROCESS_TIMEOUT'));},150000);c.stdout.on('data',b=>stdout+=b);c.stderr.on('data',b=>stderr+=b);c.on('error',reject);c.on('close',code=>{clearTimeout(timer);let report;try{report=JSON.parse(stdout);}catch{}resolve({code,stdout,stderr,report});});});
}finally{await rm(d,{recursive:true,force:true});}}
const listen=async server=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));return 'http://127.0.0.1:'+server.address().port;};

test('generic cold reader contains no provider vocabulary, addresses, repository imports, credentials or clock injection',async()=>{const source=await readFile(new URL('../scripts/cold-agent.py',import.meta.url),'utf8');assert(!/WHP|Wheeler|Hubbell|standing\.test|\/v1\/|import.*(?:fixtures|producer|service\.mjs)/.test(source));for(const property of [/len\(sys.argv\)==2/,/--network=none/,/--read-only/,/--cap-drop=ALL/,/--user=65534:65534/,/TEST_SELF_CONSISTENT_ROOT/])assert.match(source,property);});

test('three cold processes execute actual TEST propagation and reject adversarial substitutions',{timeout:600000},async(t)=>{
  const f=fixture({at:clock()}),a=await setup({f,clock});let intercept=null,providers=[],catalogQueries=[];
  const proxy={get origin(){return a.service.origin;},handle:async req=>intercept?intercept(req):a.service.handle(req)};
  const original=nodeServer(proxy),migrated=nodeServer(proxy),oldOrigin=await listen(original),newOrigin=await listen(migrated);
  a.service.origin=oldOrigin;a.service._resolutionUrl=oldOrigin+RESOLUTION_PATH;
  const catalog=createServer((req,res)=>{const u=new URL(req.url,'http://127.0.0.1');catalogQueries.push(Object.fromEntries(u.searchParams));res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({interface:'capability-catalog-v1',providers}));});
  const catalogOrigin=await listen(catalog);a.service.catalogUrl=catalogOrigin+'/capabilities';
  const candidate={id:'independent-directory-entry-7',capability_class:CAPABILITY_CLASS,properties:STANDING_CAPABILITY.requirements,scopes:[f.scope],jurisdictions:[f.jurisdiction],resolution_url:a.service.resolutionUrl};
  providers=[{...candidate,id:'unrelated-capability',capability_class:'urn:capability:document-compression:1'},{...candidate,id:'missing-independent-verification',properties:['explicit-bounds']},candidate];
  const later={object:{id:'later-unwarranted-object',version:'2',content:{statement:'A new action has no inherited authority.'}},action:{operation:'EXECUTE',scope:f.scope,jurisdiction:f.jurisdiction},need_interface:{version:'STANDING-NEED-v1',vendor_neutral:true,capability:STANDING_CAPABILITY,catalog:{interface:'capability-catalog-v1',url:a.service.catalogUrl}}};
  assert(!/WHP|Wheeler|Hubbell|whp/i.test(JSON.stringify(later)));
  await rm(E,{recursive:true,force:true});await mkdir(E,{recursive:true});const negatives=[],reports={};let bytes;
  try{const p=await a.purchase();assert.equal(p.response.status,200,p.bytes);bytes=p.bytes;const mark=JSON.parse(bytes),id=mark.payload.purchase_id;
    const passed=async(name,input)=>{const r=await cold(input);await writeFile(`${E}/${name}.stdout.json`,r.stdout);await writeFile(`${E}/${name}.stderr.txt`,r.stderr);assert.equal(r.code,0,r.stdout+r.stderr);assert.equal(r.report.verified,true);assert.equal(r.report.environment,'TEST');assert.equal(r.report.payment_status,402);assert.equal(r.report.payment_authorizations_created,0);assert.equal(r.report.input_files,1);assert.equal(r.report.prior_provider_configuration,false);assert.equal(r.report.repository_imports,false);assert.equal(r.report['PROPAGATION-PROVEN'],'TEST');assert.equal(a.rail.settleCalls,1);assert.equal(a.rail.transfers,1);reports[name]=r.report;return r.report;};
    await t.test('A: ONLY completed Mark reaches meaning, independent replay, profile, fresh status, capability, contract and 402',async()=>{const r=await passed('A',bytes);assert.equal(r.independent_verifier.current_standing,'ACTIVE');assert.equal(r.independent_verifier.live_completion_verified,false);assert.equal(r.root_admission,'TEST_SELF_CONSISTENT_ROOT');assert.equal(r.sandbox.producer_source,false);assert.equal(r.sandbox.private_keys,false);assert.equal(r.sandbox.network,'none');assert.equal(r.mark_sha256,hashBytes(bytes));await writeFile(E+'/A.only-input.json',bytes);});
    await t.test('B: ONLY external object/action and neutral catalog interface discovers by capabilities, never provider name',async()=>{const input=JSON.stringify(later),r=await passed('B',input);assert.equal(r.need.result,'NO_STANDING_EVIDENCE');assert.equal(r.catalog_provider_count,3);assert.equal(r.compatible_provider_count,1);assert.deepEqual(r.external_object.id,later.object.id);assert.equal(r.contemplated_action.operation,'EXECUTE');assert.equal(r.independent_resolution_verifier.historical_issuance,'NOT_PRESENT');assert.equal(r.provider_selection_rule,'CAPABILITY_CLASS_PROPERTIES_SCOPE_JURISDICTION_NOT_NAME');assert(catalogQueries.some(q=>q.capability_class===CAPABILITY_CLASS));await writeFile(E+'/B.only-input.json',input);});
    await t.test('C: first Mark verified before new unsupported object/action, neutral recognition, rediscovery and second 402',async()=>{const r=await passed('C',JSON.stringify({first:Buffer.from(bytes).toString('base64'),later}));assert.equal(r.ordering,'FIRST_MARK_VERIFIED_BEFORE_LATER_NEED_DISCOVERY');assert.equal(r.first.independent_verifier.current_standing,'ACTIVE');assert.equal(r.later.need.result,'NO_STANDING_EVIDENCE');assert.equal(r.first.provider_id,r.later.provider_id);assert.equal(r.historical_mark_unchanged,true);assert.notEqual(r.later.external_object.id,r.first.meaning.object.id);});
    await t.test('stable resolution migrates service/registry to a new origin without rewriting historical Mark or charging again',async()=>{a.service.origin=newOrigin;intercept=async req=>new URL(req.url).origin===oldOrigin&&new URL(req.url).pathname!==RESOLUTION_PATH?new Response('former service gone',{status:410}):a.service.handle(req);try{const r=await passed('migration',bytes);assert(r.trace.some(x=>x.url===oldOrigin+RESOLUTION_PATH));assert(r.trace.some(x=>x.url.startsWith(newOrigin+'/')&&x.status===402));assert.equal(r.independent_verifier.current_discovery.service_origin,newOrigin);assert.equal(r.mark_sha256,hashBytes(bytes));}finally{intercept=null;}});
    const rejected=async(name,input=bytes)=>{const r=await cold(input);negatives.push({name,...r.report,exit_code:r.code});assert.notEqual(r.code,0,name+' unexpectedly succeeded');assert.equal(a.rail.settleCalls,1);};
    await t.test('missing immutable discovery identity fails without hidden provider knowledge',async()=>{const m=JSON.parse(bytes);delete m.payload.discovery;await rejected('missing identity',canonical(m));});
    await t.test('altered original Mark signature fails',async()=>{const m=JSON.parse(bytes);m.signature=(m.signature[0]==='A'?'B':'A')+m.signature.slice(1);await rejected('tampered signature',canonical(m));});
    await t.test('issuer-only signature cannot enlarge root-authorized meaning or choose another verifier',async()=>{for(const mutate of [p=>p.protocol.document.meaning.establishes='/payload/issuer',p=>p.protocol.verifier_sha256='00'.repeat(32)]){const m=JSON.parse(bytes);mutate(m.payload);await rejected('issuer-only contract substitution',canonical(seal(m.protected.type,m.payload,f.issuer.privateKey)));}});
    await t.test('different discovered root cannot appoint itself',async()=>{intercept=async req=>{const r=await a.service.handle(req);if(new URL(req.url).pathname===RESOLUTION_PATH){const j=await r.json();j.payload.root_key_id='00'.repeat(32);return Response.json(j);}return r;};try{await rejected('root substitution');}finally{intercept=null;}});
    await t.test('changed downloaded verifier is rejected before any execution',async()=>{intercept=async req=>new URL(req.url).pathname.startsWith('/verification/')?new Response("raise Exception('untrusted code')\n"):a.service.handle(req);try{await rejected('verifier substitution');}finally{intercept=null;}});
    await t.test('unavailable immutable profile and current purchase contract fail rather than silently succeeding',async()=>{for(const target of ['/v1/immutable/'+mark.payload.protocol.document.profile.sha256,'/v1/contract']){intercept=async req=>new URL(req.url).pathname===target?new Response('missing',{status:404}):a.service.handle(req);try{await rejected('missing '+target);}finally{intercept=null;}}});
    await t.test('freshly signed stale discovery resolution is not current discovery',async()=>{intercept=async req=>{const r=await a.service.handle(req);if(new URL(req.url).pathname===RESOLUTION_PATH){const j=await r.json();j.payload.observed_at=clock()-600;j.payload.valid_until=clock()-300;return Response.json(seal(j.protected.type,j.payload,f.issuer.privateKey));}return r;};try{await rejected('stale discovery');}finally{intercept=null;}});
    await t.test('freshly signed stale registry is not current standing',async()=>{intercept=async req=>{const r=await a.service.handle(req);if(new URL(req.url).pathname==='/v1/registry/'+id){const j=await r.json();j.payload.observed_at=clock()-600;j.payload.valid_until=clock()-300;return Response.json(seal(j.protected.type,j.payload,f.issuer.privateKey));}return r;};try{await rejected('stale registry');}finally{intercept=null;}});
    await t.test('payment terms cannot be substituted underneath a signed current-service commitment',async()=>{intercept=async req=>{const r=await a.service.handle(req);if(new URL(req.url).pathname==='/v1/contract'){const j=await r.json();j.purchase.requirements.amount='123';return Response.json(j);}return r;};try{await rejected('payment term substitution');}finally{intercept=null;}});
    await t.test('neutral discovery refuses incompatible catalog rather than falling back to a memorized provider',async()=>{const saved=providers;providers=providers.slice(0,2);try{await rejected('no compatible provider',JSON.stringify(later));}finally{providers=saved;}});
    await t.test('withdrawal defeats current reliance but historical bytes and paid retrieval are unchanged',async()=>{const previous=(await a.store.events(id)).at(-1);await a.service.applyRegistryCommand(seal('WHP-REGISTRY-COMMAND-v1',{purchase_id:id,expected_previous_hash:hash(previous),status:'WITHDRAWN',reason:'Adversarial TEST withdrawal',at:clock()},f.root.privateKey));await rejected('withdrawn registry');assert.equal(await(await a.request('GET','/v1/purchases/'+id+'/result')).text(),bytes);});
    assert.deepEqual(Object.keys(reports).sort(),['A','B','C','migration']);assert(negatives.length>=12&&negatives.every(x=>x.exit_code===1&&x.verified===false),'ALL_NEGATIVE_CASES_MUST_REJECT');
    await writeFile(E+'/report.json',JSON.stringify({verified:true,environment:'TEST','PROPAGATION-PROVEN':'TEST',tests:['A','B','C'],test_reports:Object.fromEntries(Object.keys(reports).map(k=>[k,k+'.stdout.json'])),mark_sha256:hashBytes(bytes),catalog_queries:catalogQueries,original_simulated_settlements:a.rail.settleCalls,simulated_transfers:a.rail.transfers,next_payment_authorizations:0,durable_byte_identical_retrieval:true,service_origin_migration_proven:true,negative_cases:negatives.length,production_completion:false,open_internet_catalog_or_institutional_root_admission:false},null,2)+'\n');
  }finally{await writeFile(E+'/adversarial-cases.json',JSON.stringify(negatives,null,2)+'\n');await Promise.all([original,migrated,catalog].map(s=>new Promise(r=>s.close(r))));await a.store.close();}
});
