import test from 'node:test';import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';import {mkdtempSync,writeFileSync,readFileSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {canonical,parseStrict,hash,clone,seal,openSeal,publicDer,keyId,hashBytes} from '../src/canonical.mjs';
import {evaluate} from '../src/evaluator.mjs';import {validateSubmission} from '../src/validation.mjs';import {keccak} from '../src/keccak.mjs';
import {fixture,setup,resignTarget,paymentFor,FakeRail,NOW,refreshTrustStatus} from './fixtures.mjs';
const verifier=new URL('../verify/verify_mark.py',import.meta.url).pathname;
function independent(bytes,pin,extra=[]){const dir=mkdtempSync(join(tmpdir(),'whp-verify-'));try{const p=join(dir,'mark.json');writeFileSync(p,bytes);const r=spawnSync('python',[verifier,p,'--root-pin',pin,'--allow-test',...extra],{encoding:'utf8'});return {status:r.status,stdout:r.stdout,stderr:r.stderr};}finally{rmSync(dir,{recursive:true,force:true});}}

test('strict JSON rejects duplicate keys before information is lost',()=>assert.throws(()=>parseStrict('{"a":1,"a":2}'),/DUPLICATE_JSON_KEY/));
test('strict JSON rejects nested duplicates',()=>assert.throws(()=>parseStrict('{"a":{"x":1,"x":2}}'),/DUPLICATE_JSON_KEY/));
test('strict JSON rejects nonintegral numbers, unsafe integers, negative zero and lone surrogates',()=>{for(const s of ['0.2','9007199254740992','-0','"\\ud800"'])assert.throws(()=>parseStrict(s));});
test('canonical ordering follows UTF-16 and preserves distinct Unicode strings',()=>{const x={'\uE000':1,'😀':2,a:'é',b:'é'};assert.equal(canonical(x),'{"a":"é","b":"é","😀":2,"":1}');assert.notEqual(hash('é'),hash('é'));});
test('Keccak known vectors agree with public Ethereum event selectors',()=>{assert.equal(keccak(''),'0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470');assert.equal(keccak('Transfer(address,address,uint256)'),'0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef');});
test('source-locked COPY establishes only its declared operation',()=>{const f=fixture();const d=evaluate(f.submission,f.trustBundle,f.rootPin,NOW);assert.equal(d.outcome,'ESTABLISHED');assert.deepEqual(d.permitted_operations,['INFORM','RECOMMEND']);assert.equal(d.components.ACTION_BOUNDARY,'NOT_ASSESSED');});
for(const [name,change,rule] of [
 ['qualifier stripping',n=>n.qualifiers.pop(),'QUALIFIERS_PRESERVED'],
 ['unknown concealment',n=>n.unknowns=[],'UNKNOWNS_PRESERVED'],
 ['changed copy content',n=>n.content.count=99,'EXACT_TRANSFORMATION'],
 ['epistemic promotion',n=>n.epistemic_status='FINDING','EXACT_TRANSFORMATION'],
 ['force escalation',n=>n.operations.push('EXECUTE'),'NO_FORCE_ESCALATION'],
 ['withdrawn source',n=>n.status='WITHDRAWN','SOURCE_ACTIVE'],
 ['jurisdiction drift',n=>n.jurisdiction='unrelated','SOURCE_BOUNDS'],
 ['temporal narrowing below requested bounds',n=>n.valid_until=NOW+10,'SOURCE_TIME']
])test(name+' cannot receive a mark',()=>{const f=fixture(),s=resignTarget(f,change),d=evaluate(s,f.trustBundle,f.rootPin,NOW);assert.equal(d.outcome,'NOT_ESTABLISHED');assert(d.checks.some(c=>c.rule===rule&&!c.passed));});
test('client-declared authority without an admitted key fails closed',()=>{const f=fixture();f.submission.nodes[0]=seal('WHP-SOURCE-ATTESTATION-v1',f.submission.nodes[0].payload,f.buyer.privateKey);assert.equal(evaluate(f.submission,f.trustBundle,f.rootPin,NOW).outcome,'NOT_ESTABLISHED');});
test('a different embedded root cannot appoint itself',()=>{const f=fixture(),g=fixture();assert.throws(()=>evaluate(f.submission,f.trustBundle,g.rootPin,NOW),/UNTRUSTED_ROOT/);});
test('explicit source revocation defeats standing',()=>{const f=fixture();f.trustBundle.revocations.push(seal('WHP-KEY-REVOCATION-v1',{key_id:keyId(publicDer(f.source.privateKey)),effective_at:NOW-1,reason:'test revocation'},f.root.privateKey));refreshTrustStatus(f);assert.equal(evaluate(f.submission,f.trustBundle,f.rootPin,NOW).outcome,'NOT_ESTABLISHED');});
test('blocking unknown prevents EXECUTE',()=>{const f=fixture();f.submission.requested_operation='EXECUTE';assert.equal(evaluate(f.submission,f.trustBundle,f.rootPin,NOW).outcome,'NOT_ESTABLISHED');});
test('unrelated source cannot disappear from the submitted graph',()=>{const f=fixture(),n=clone(f.submission.nodes[0].payload);n.id='orphan';f.submission.nodes.push(seal('WHP-SOURCE-ATTESTATION-v1',n,f.source.privateKey));assert.equal(evaluate(f.submission,f.trustBundle,f.rootPin,NOW).outcome,'NOT_ESTABLISHED');});

test('invalid requests stop before storage and all payment work',async()=>{const a=await setup();try{const before=a.store.calls;for(const raw of ['{}','{"x":1,"x":2}','{"version":"wrong"}']){const r=await a.request('POST','/v1/evaluations',raw);assert.equal(r.status,400);}assert.equal(a.store.calls,before);assert.equal(a.rail.verifyCalls,0);assert.equal(a.rail.settleCalls,0);}finally{await a.store.close();}});
test('first paid test issuance independently verifies in Python',async()=>{const a=await setup();try{const p=await a.purchase();assert.equal(p.response.status,200,p.bytes);assert.equal(a.rail.transfers,1);const v=independent(p.bytes,a.f.rootPin);assert.equal(v.status,0,v.stdout+v.stderr);const r=JSON.parse(v.stdout);assert.equal(r.evaluation_replay,'VERIFIED');assert.equal(r.environment,'TEST');assert.equal(r.live_completion_verified,false);}finally{await a.store.close();}});
test('a failed assessment is paid once but receives no Standing Mark',async()=>{const a=await setup();try{const s=resignTarget(a.f,n=>n.qualifiers=[]),p=await a.purchase(s);assert.equal(p.response.status,200,p.bytes);const e=JSON.parse(p.bytes);assert.equal(e.protected.type,'WHP-STANDING-ASSESSMENT-v1');assert.equal(e.payload.mark_id,null);assert.equal(a.rail.transfers,1);const v=independent(p.bytes,a.f.rootPin);assert.equal(v.status,0,v.stdout);}finally{await a.store.close();}});
test('durable retrieval and identical POST return exactly the original bytes with no payment calls',async()=>{const a=await setup();try{const p=await a.purchase(),id=JSON.parse(p.bytes).payload.purchase_id;const before=[a.rail.verifyCalls,a.rail.settleCalls];for(let i=0;i<4;i++){const r=await a.request('GET','/v1/purchases/'+id+'/result');assert.equal(await r.text(),p.bytes);}
 const replay=await a.request('POST','/v1/evaluations',p.raw);assert.equal(await replay.text(),p.bytes);assert.deepEqual([a.rail.verifyCalls,a.rail.settleCalls],before);}finally{await a.store.close();}});
test('same buyer reference with changed object is a conflict, not another purchase',async()=>{const a=await setup();try{const q=await a.start(),s=clone(a.f.submission);s.requested_operation='RECOMMEND';const r=await a.request('POST','/v1/evaluations',canonical(s));assert.equal(r.status,409);assert.equal(a.rail.settleCalls,0);}finally{await a.store.close();}});
test('payment nonce is bound to the exact quote and cannot buy a different input',async()=>{const a=await setup();try{const q=await a.start(),p=paymentFor(q.quote);p.payload.authorization.nonce='0x'+'ff'.repeat(32);const r=await a.request('POST','/v1/evaluations',q.raw,p);assert.equal(r.status,400);assert.equal(a.rail.verifyCalls,0);assert.equal(a.rail.settleCalls,0);}finally{await a.store.close();}});
for(const [name,mutate] of [['recipient',p=>p.payload.authorization.to='0x'+'aa'.repeat(20)],['amount',p=>p.payload.authorization.value='2'],['network',p=>p.accepted.network='eip155:1'],['asset',p=>p.accepted.asset='0x'+'aa'.repeat(20)],['resource',p=>p.resource.url='https://evil.invalid/']])
test('wrong '+name+' is rejected before facilitator verification',async()=>{const a=await setup();try{const q=await a.start(),p=paymentFor(q.quote);mutate(p);const r=await a.request('POST','/v1/evaluations',q.raw,p);assert.equal(r.status,400);assert.equal(a.rail.verifyCalls,0);assert.equal(a.rail.settleCalls,0);}finally{await a.store.close();}});
test('failed facilitator verification never settles or issues',async()=>{const a=await setup();try{a.rail.failVerify=true;const q=await a.start();const r=await a.request('POST','/v1/evaluations',q.raw,paymentFor(q.quote));assert.equal(r.status,503);assert.equal(a.rail.settleCalls,0);const row=await a.store.get(q.quote.payload.purchase_id);assert.equal(row.state,'QUOTED');}finally{await a.store.close();}});
test('concurrent same-purchase requests converge on one transfer and one immutable result',async()=>{const a=await setup();try{const q=await a.start(),p=paymentFor(q.quote);const responses=await Promise.all(Array.from({length:8},()=>a.request('POST','/v1/evaluations',q.raw,p)));assert(responses.some(r=>r.status===200));const r=await a.request('GET','/v1/purchases/'+q.quote.payload.purchase_id+'/result');assert.equal(r.status,200);assert.equal(a.rail.transfers,1);assert.equal((await a.store.events(q.quote.payload.purchase_id)).length,1);}finally{await a.store.close();}});
test('an uncertain settlement never becomes an optimistic mark',async()=>{const a=await setup();try{a.rail.reveal=false;a.rail.mode='timeout-after-transfer';const p=await a.purchase();assert.equal(p.response.status,202);const id=p.quote.payload.purchase_id;assert.equal((await a.store.get(id)).state,'SETTLING');assert.equal((await a.store.events(id)).length,0);a.rail.reveal=true;const r=await a.request('POST','/v1/purchases/'+id+'/recover');assert.equal(r.status,200,await r.clone().text());assert.equal(a.rail.transfers,1);assert.equal(a.rail.settleCalls,1);}finally{await a.store.close();}});
test('lost response after settlement recovers exact stored authorization, not a second charge',async()=>{const a=await setup();try{a.rail.mode='timeout-after-transfer';const p=await a.purchase();assert.equal(p.response.status,200,p.bytes);assert.equal(a.rail.transfers,1);assert.equal(a.rail.settleCalls,1);}finally{await a.store.close();}});
test('crash after durable settlement resumes signing without another settlement',async()=>{let once=true;const a=await setup({hooks:{afterDurableSettlement:()=>{if(once){once=false;throw new Error('injected crash');}}}});try{const p=await a.purchase();assert.equal(p.response.status,503);const r=await a.request('POST','/v1/purchases/'+p.quote.payload.purchase_id+'/recover');assert.equal(r.status,200,await r.clone().text());assert.equal(a.rail.settleCalls,1);assert.equal(a.rail.transfers,1);}finally{await a.store.close();}});
test('lost HTTP response after durable issuance retrieves byte-identically',async()=>{let once=true,captured;const a=await setup({hooks:{afterPersistResult:b=>{captured=b;if(once){once=false;throw new Error('response lost');}}}});try{const p=await a.purchase();assert.equal(p.response.status,503);const r=await a.request('GET','/v1/purchases/'+p.quote.payload.purchase_id+'/result');assert.equal(await r.text(),captured);assert.equal(a.rail.transfers,1);}finally{await a.store.close();}});
test('a fresh process connection retrieves durable SQLite bytes',async()=>{const dir=mkdtempSync(join(tmpdir(),'whp-db-')),filename=join(dir,'ledger.sqlite');const f=fixture(),rail=new FakeRail();let a=await setup({filename,f,rail});try{const p=await a.purchase();const id=JSON.parse(p.bytes).payload.purchase_id;await a.store.close();a=await setup({filename,f,rail});const r=await a.request('GET','/v1/purchases/'+id+'/result');assert.equal(await r.text(),p.bytes);assert.equal(rail.settleCalls,1);}finally{await a.store.close();rmSync(dir,{recursive:true,force:true});}});
test('buyer A cannot retrieve buyer B private result',async()=>{const a=await setup();try{const p=await a.purchase(),f=fixture();const r=await a.request('GET','/v1/purchases/'+p.quote.payload.purchase_id+'/result','',null,f.buyer.privateKey);assert.notEqual(r.status,200);}finally{await a.store.close();}});
test('independent verifier rejects altered signatures and a wrong root pin',async()=>{const a=await setup();try{const p=await a.purchase(),e=JSON.parse(p.bytes);e.payload.object.id='substituted';assert.equal(independent(canonical(e),a.f.rootPin).status,1);assert.equal(independent(p.bytes,'00'.repeat(32)).status,1);}finally{await a.store.close();}});
test('independent replay rejects issuer-signed false promotion',async()=>{const a=await setup();try{const p=await a.purchase();const e=JSON.parse(p.bytes),payload=e.payload;payload.decision_record.permitted_operations.push('EXECUTE');payload.decision_record_ref='urn:sha256:'+hash(payload.decision_record);const counterfeit=seal(e.protected.type,payload,a.f.issuer.privateKey);const v=independent(canonical(counterfeit),a.f.rootPin);assert.equal(v.status,1);assert.match(v.stdout,/EVALUATION_REPLAY_MISMATCH/);}finally{await a.store.close();}});
test('public registry binds the exact signed file and independent freshness check passes',async()=>{const a=await setup();const dir=mkdtempSync(join(tmpdir(),'whp-registry-'));try{const p=await a.purchase();const r=await a.request('GET','/v1/registry/'+p.quote.payload.purchase_id);const path=join(dir,'registry.json');writeFileSync(path,await r.text());const v=independent(p.bytes,a.f.rootPin,['--registry',path,'--at',String(NOW)]);assert.equal(v.status,0,v.stdout);assert.equal(JSON.parse(v.stdout).current_standing,'ACTIVE');const stale=independent(p.bytes,a.f.rootPin,['--registry',path,'--at',String(NOW+600)]);assert.equal(stale.status,1);}finally{await a.store.close();rmSync(dir,{recursive:true,force:true});}});
test('withdrawal appends history, does not rewrite a Mark, and cannot silently reactivate it',async()=>{const a=await setup();try{const p=await a.purchase(),id=p.quote.payload.purchase_id;const prior=(await a.store.events(id)).at(-1);const cmd=seal('WHP-REGISTRY-COMMAND-v1',{purchase_id:id,expected_previous_hash:hash(prior),status:'WITHDRAWN',reason:'Test withdrawal',at:NOW},a.f.root.privateKey);await a.service.applyRegistryCommand(cmd);assert.equal((await a.store.events(id)).length,2);const r=await a.request('GET','/v1/purchases/'+id+'/result');assert.equal(await r.text(),p.bytes);const last=(await a.store.events(id)).at(-1);await assert.rejects(()=>a.service.applyRegistryCommand(seal('WHP-REGISTRY-COMMAND-v1',{...cmd.payload,expected_previous_hash:hash(last),status:'ACTIVE'},a.f.root.privateKey)),/REGISTRY_TERMINAL_STATUS/);}finally{await a.store.close();}});
for(const [name,change] of [['wrong envelope type',n=>n.protected.type='OTHER-v1'],['wrong algorithm',n=>n.protected.algorithm='RSA'],['wrong canonicalization',n=>n.protected.canonicalization='ordinary-json'],['malformed signature',n=>n.signature='not-a-signature']]){
  test('invalid '+name+' is rejected before storage or payment',async()=>{const x=await setup();try{const s=clone(x.f.submission);change(s.nodes[0]);const r=await x.request('POST','/v1/evaluations',canonical(s));assert.equal(r.status,400);assert.equal(x.store.calls,0);assert.equal(x.rail.verifyCalls,0);assert.equal(x.rail.settleCalls,0);}finally{await x.store.close();}});
}
