import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,writeFileSync,mkdtempSync,rmSync,readdirSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {spawnSync} from 'node:child_process';
import {setup,fixture,refreshTrustStatus,NOW} from './fixtures.mjs';import {canonical,parseStrict,exact,hash,hashBytes,seal,clone} from '../src/canonical.mjs';import {validateTrust} from '../src/authority.mjs';import {assembleResult} from '../src/mark.mjs';import {protocol,CONTRACT_HASH,VERIFIER_HASH,SCHEMA_HASH,CAPABILITY_ID} from '../src/protocol.mjs';import {profile,PROFILE_HASH} from '../src/profile.mjs';import {resolution} from '../src/discovery.mjs';import {recognizeStandingNeed,compatibleProviders,STANDING_CAPABILITY} from '../src/need.mjs';import resultSchema from '../schemas/result.schema.json' with {type:'json'};import {validateWire} from '../src/wire-schema.mjs';
function verify(bytes,pin,{registry,resolution:resolve,at=NOW,allowTest=true}={}){const d=mkdtempSync(join(tmpdir(),'v1-verifier-'));try{writeFileSync(join(d,'mark.json'),bytes);const args=['verify/verify_mark.py',join(d,'mark.json'),'--root-pin',pin,'--at',String(at)];if(allowTest)args.push('--allow-test');if(registry){writeFileSync(join(d,'registry.json'),canonical(registry));args.push('--registry',join(d,'registry.json'));}if(resolve){writeFileSync(join(d,'resolution.json'),canonical(resolve));args.push('--resolution',join(d,'resolution.json'));}const p=spawnSync('python3',args,{encoding:'utf8'});return {...p,report:JSON.parse(p.stdout)};}finally{rmSync(d,{recursive:true,force:true});}}
const get=async(a,path)=>{const r=await a.service.handle(new Request(a.service.origin+path));assert.equal(r.status,200,await r.clone().text());return r.json();};
test('frozen public v1 manifest, embedded profile, schema, verifier and root authorization commitments agree',()=>{const p=spawnSync('python3',['scripts/freeze-contract.py','--check'],{encoding:'utf8'});assert.equal(p.status,0,p.stdout+p.stderr);assert.equal(hash(protocol().document),CONTRACT_HASH);assert.equal(hash(resultSchema),SCHEMA_HASH);assert.equal(hash(profile()),PROFILE_HASH);assert.equal(hashBytes(readFileSync('verify/verify_mark.py')),VERIFIER_HASH);assert.deepEqual(readdirSync('public/verification'),[VERIFIER_HASH+'.py']);const f=fixture();assert.equal(f.trustBundle.profile_authorization.payload.contract_hash,CONTRACT_HASH);assert.equal(f.trustBundle.profile_authorization.payload.verifier_sha256,VERIFIER_HASH);});

test('JS and independent Python canonicalization agree on UTF-16 ordering, escaping and exact safe-integer data',()=>{const value={'\ue000':'a','𐀀':'b',x:[null,true,false,9007199254740991,-9007199254740991,'é','e\u0301','\n\t\u0000','"\\']},d=mkdtempSync(join(tmpdir(),'canonical-'));try{const p=join(d,'input');writeFileSync(p,JSON.stringify(value));const py=spawnSync('python3',['-c',"import importlib.util,sys;s=importlib.util.spec_from_file_location('v','verify/verify_mark.py');m=importlib.util.module_from_spec(s);s.loader.exec_module(m);print(m.canonical(m.read(sys.argv[1])[0]),end='')",p],{encoding:'utf8'});assert.equal(py.status,0,py.stderr);assert.equal(py.stdout,canonical(value));}finally{rmSync(d,{recursive:true,force:true});}});

test('strict JSON parity rejects duplicates, fractional or exponent tokens, negative zero, unsafe integers and lone surrogates',()=>{for(const text of ['{"a":1,"a":2}','1.0','1e0','-0','9007199254740992','"\\ud800"']){assert.throws(()=>parseStrict(text));const d=mkdtempSync(join(tmpdir(),'strict-json-'));try{const p=join(d,'bad');writeFileSync(p,text);const py=spawnSync('python3',['-c',"import importlib.util,sys;s=importlib.util.spec_from_file_location('v','verify/verify_mark.py');m=importlib.util.module_from_spec(s);s.loader.exec_module(m);m.read(sys.argv[1])",p],{encoding:'utf8'});assert.notEqual(py.status,0,text);}finally{rmSync(d,{recursive:true,force:true});}}});

test('canonical JSON rejects sparse arrays, accessors, symbols and hidden properties; closed fields cannot collide through delimiters',()=>{const sparse=new Array(1),getter={get value(){throw Error('GETTER_EXECUTED');}},hidden=Object.defineProperty({},'x',{value:1}),symbol={[Symbol('x')]:1};for(const x of [sparse,getter,hidden,symbol])assert.throws(()=>canonical(x),e=>e.message!=='GETTER_EXECUTED');assert.throws(()=>exact({'a\0b':1},['a','b']));assert.throws(()=>exact({'a,b':1},['a','b']));assert.throws(()=>canonical([undefined]));});

test('root-authorized contract, profile and program cannot be switched by an issuer signature or mutable web content',()=>{for(const field of ['profile_hash','contract_hash','verifier_sha256']){const f=fixture();f.trustBundle.profile_authorization.payload[field]='00'.repeat(32);f.trustBundle.profile_authorization=seal('WHP-PROFILE-AUTHORIZATION-v1',f.trustBundle.profile_authorization.payload,f.root.privateKey);refreshTrustStatus(f);assert.throws(()=>validateTrust(f.trustBundle,f.rootPin,NOW));}});

test('closed semantic schema and independent verifier reject extra top-level, profile, discovery, authority and commerce fields',async()=>{const a=await setup();try{const p=await a.purchase();for(const path of [[],['discovery'],['protocol'],['authority'],['commerce'],['standing'],['decision_record']]){const m=JSON.parse(p.bytes);let target=m.payload;for(const key of path)target=target[key];target.extensions={claim:'all truth'};const forged=seal(m.protected.type,m.payload,a.f.issuer.privateKey);assert.throws(()=>validateWire(forged,resultSchema));assert.equal(verify(canonical(forged),a.f.rootPin).status,1);} }finally{await a.store.close();}});

test('an exact rule result cannot carry a different issuer-written semantic explanation',async()=>{const a=await setup();try{const p=await a.purchase(),m=JSON.parse(p.bytes);m.payload.decision_record.checks[0].detail='All unobserved facts are now established.';m.payload.decision_record_ref='urn:sha256:'+hash(m.payload.decision_record);const e=seal(m.protected.type,m.payload,a.f.issuer.privateKey);assert.throws(()=>validateWire(e,resultSchema));assert.equal(verify(canonical(e),a.f.rootPin).status,1);}finally{await a.store.close();}});

test('historical verification without registry never reports current standing; TEST cannot be promoted to LIVE',async()=>{const a=await setup();try{const p=await a.purchase();const v=verify(p.bytes,a.f.rootPin);assert.equal(v.status,0,v.stdout);assert.equal(v.report.historical_issuance,'VERIFIED');assert.equal(v.report.current_standing,'NOT_CHECKED');assert.equal(v.report.live_completion_verified,false);const live=verify(p.bytes,a.f.rootPin,{allowTest:false});assert.equal(live.status,1);assert.match(live.report.error,/TEST_ARTIFACT_NOT_LIVE/);}finally{await a.store.close();}});

test('fresh registry withdrawal changes current standing but not historical verification or exact retrieval bytes',async()=>{const a=await setup();try{const p=await a.purchase(),m=JSON.parse(p.bytes),id=m.payload.purchase_id;const previous=(await a.store.events(id)).at(-1);await a.service.applyRegistryCommand(seal('WHP-REGISTRY-COMMAND-v1',{purchase_id:id,expected_previous_hash:hash(previous),status:'WITHDRAWN',reason:'Public v1 withdrawal proof',at:NOW},a.f.root.privateKey));const registry=await get(a,'/v1/registry/'+id),v=verify(p.bytes,a.f.rootPin,{registry});assert.equal(v.status,0,v.stdout);assert.equal(v.report.historical_issuance,'VERIFIED');assert.equal(v.report.current_standing,'WITHDRAWN');assert.equal(await(await a.request('GET','/v1/purchases/'+id+'/result')).text(),p.bytes);}finally{await a.store.close();}});

test('stale current registry failure retains historical verification and never returns ACTIVE',async()=>{const a=await setup();try{const p=await a.purchase(),m=JSON.parse(p.bytes),registry=await get(a,'/v1/registry/'+m.payload.purchase_id);registry.payload.observed_at=NOW-600;registry.payload.valid_until=NOW-300;const v=verify(p.bytes,a.f.rootPin,{registry:seal(registry.protected.type,registry.payload,a.f.issuer.privateKey)});assert.equal(v.status,1);assert.equal(v.report.historical_issuance,'VERIFIED');assert.equal(v.report.current_standing,'NOT_VERIFIED');assert.match(v.report.error,/REGISTRY_SNAPSHOT_STALE/);}finally{await a.store.close();}});

test('current discovery requires a distinct admitted DISCOVERY role, fresh trust, same immutable identity and matching environment',async()=>{const a=await setup();try{const p=await a.purchase();const good=resolution(a.service);assert.equal(verify(p.bytes,a.f.rootPin,{resolution:good}).status,0);for(const change of [r=>r.payload.resolution_id='urn:other:resolution',r=>r.payload.capability_id='urn:other:capability',r=>r.payload.root_key_id='00'.repeat(32),r=>r.payload.valid_until=NOW-1,r=>r.payload.environment='LIVE',r=>r.payload.artifacts[0].sha256='00'.repeat(32)]){const r=clone(good);change(r);assert.equal(verify(p.bytes,a.f.rootPin,{resolution:seal(r.protected.type,r.payload,a.f.issuer.privateKey)}).status,1);}const cert=a.f.trustBundle.certificates[0];cert.payload.roles=cert.payload.roles.filter(x=>x!=='DISCOVERY');a.f.trustBundle.certificates[0]=seal(cert.protected.type,cert.payload,a.f.root.privateKey);refreshTrustStatus(a.f);assert.throws(()=>resolution(a.service));}finally{await a.store.close();}});

test('registry and discovery signed artifacts cannot substitute for historical Mark or one another',async()=>{const a=await setup();try{const p=await a.purchase(),m=JSON.parse(p.bytes),r=resolution(a.service),registry=await get(a,'/v1/registry/'+m.payload.purchase_id);assert.equal(verify(canonical(r),a.f.rootPin).status,1);assert.equal(verify(p.bytes,a.f.rootPin,{resolution:registry}).status,1);assert.equal(verify(p.bytes,a.f.rootPin,{registry:r}).status,1);}finally{await a.store.close();}});

test('durable quotation fixes discovery identity before payment and recovery does not recompute it from moved service',async()=>{const a=await setup();try{a.service._resolutionUrl='https://resolver.test.invalid/stable-capability';const q=await a.start(),row=await a.store.get(q.quote.payload.purchase_id);assert.equal(row.discovery_identity.resolution_url,a.service.resolutionUrl);a.service._resolutionUrl='https://different.test.invalid/not-the-original';const p=await a.purchase();assert.equal(p.response.status,200,p.bytes);assert.equal(JSON.parse(p.bytes).payload.discovery.resolution_url,row.discovery_identity.resolution_url);assert.equal(a.rail.transfers,1);}finally{await a.store.close();}});

test('vendor-neutral requirements preserve each independently missing epistemic condition without naming a provider',()=>{const object={id:'x',version:'1',content:{}},action={operation:'INFORM',scope:'s',jurisdiction:'j'};assert.equal(recognizeStandingNeed(object,action).result,'NO_STANDING_EVIDENCE');const e={authority_established:true,provenance_sufficient:true,qualifications_preserved:true,blocking_unknowns:false,independently_verifiable:true,object_id:'x',object_version:'1',operations:['INFORM']};for(const [field,value,result] of [['authority_established',false,'INSUFFICIENT_AUTHORITY'],['provenance_sufficient',false,'PROVENANCE_INSUFFICIENT'],['qualifications_preserved',false,'QUALIFICATION_PRESERVATION_UNESTABLISHED'],['blocking_unknowns',true,'BLOCKING_UNKNOWN'],['independently_verifiable',false,'INDEPENDENTLY_VERIFIABLE_WARRANT_REQUIRED'],['object_id','different','TRANSFORMATION_WARRANT_MISSING'],['operations',[],'TRANSFORMATION_WARRANT_MISSING']]){const r=recognizeStandingNeed({...object,standing_evidence:{...e,[field]:value}},action);assert.equal(r.result,result);assert.equal(r.capability_required.vendor_neutral,true);assert(!/whp|wheeler|hubbell/i.test(JSON.stringify(r)));}const enough=recognizeStandingNeed({...object,standing_evidence:e},action);assert.equal(enough.result,'SUFFICIENT_STANDING_EVIDENCE');assert.equal(enough.capability_required,null);});

test('provider matching admits independent alternatives and is invariant under provider names and catalog order',()=>{const requirement=recognizeStandingNeed({id:'x',version:'1',content:{}},{operation:'INFORM',scope:'s',jurisdiction:'j'}),p={capability_class:STANDING_CAPABILITY.id,properties:STANDING_CAPABILITY.requirements,scopes:['s'],jurisdictions:['j']};const a={...p,id:'any-other-provider'},b={...p,id:'different-independent-provider'},bad={...p,id:CAPABILITY_ID,properties:[]};assert.deepEqual(compatibleProviders(requirement,[bad,a,b]),[a,b]);assert.deepEqual(compatibleProviders(requirement,[b,bad,a]),[b,a]);assert.deepEqual(compatibleProviders(requirement,[bad]),[]);});

test('Mark constructor replays the exact stored decision rather than signing a tampered completed row',async()=>{const a=await setup();try{const p=await a.purchase(),id=JSON.parse(p.bytes).payload.purchase_id,row=await a.store.get(id);row.state='SETTLED';row.decision.components.ACTION_BOUNDARY='ESTABLISHED';assert.throws(()=>assembleResult(row,a.f.issuer.privateKey,a.f.rootPin),/RESULT_DECISION_REPLAY/);}finally{await a.store.close();}});

test('candidate-shaped signed results have no legacy verifier fallback under the first public contract',async()=>{const a=await setup();try{const p=await a.purchase(),m=JSON.parse(p.bytes);delete m.payload.protocol;delete m.payload.discovery;const v=verify(canonical(seal(m.protected.type,m.payload,a.f.issuer.privateKey)),a.f.rootPin);assert.equal(v.status,1);assert.equal(v.report.verified,false);}finally{await a.store.close();}});
