import {mkdir,writeFile,readFile,rm} from 'node:fs/promises';import {resolve} from 'node:path';import {spawnSync} from 'node:child_process';import {sourceManifest} from './source-manifest.mjs';import {hash} from '../src/canonical.mjs';
const root=resolve(new URL('..',import.meta.url).pathname);process.chdir(root);const E='evidence/public-v1';await rm(E,{recursive:true,force:true});await mkdir(E,{recursive:true});const started=new Date().toISOString();
function run(command,args,options={}){const r=spawnSync(command,args,{encoding:'utf8',maxBuffer:32*1024*1024,timeout:600000,...options});if(r.error||r.status!==0){const e=Error((r.error?.message??'COMMAND_FAILED')+' '+command+' '+args.join(' ')+'\n'+r.stdout+'\n'+r.stderr);e.result=r;throw e;}return r;}
try{
  const before=await sourceManifest();await writeFile(E+'/source-manifest.json',JSON.stringify(before,null,2)+'\n');
  const frozen=run('python3',['scripts/freeze-contract.py','--check']);await writeFile(E+'/contract-commitments.json',frozen.stdout);
  const js=before.files.map(f=>f.path).filter(p=>p.endsWith('.mjs')),py=before.files.map(f=>f.path).filter(p=>p.endsWith('.py'));
  for(const path of js)run(process.execPath,['--check',path]);run('python3',['-c','import pathlib,sys;[(compile(pathlib.Path(p).read_text(),p,"exec")) for p in sys.argv[1:]]',...py]);
  let tests;try{tests=run(process.execPath,['--test','--test-concurrency=2',...before.files.map(f=>f.path).filter(p=>p.startsWith('test/')&&p.endsWith('.test.mjs')).sort()]);}catch(e){await writeFile(E+'/tests.tap',(e.result?.stdout??'')+(e.result?.stderr??''));throw e;}
  await writeFile(E+'/tests.tap',tests.stdout+tests.stderr);const counts=Object.fromEntries([...tests.stdout.matchAll(/^# (tests|pass|fail|cancelled|skipped|todo) (\d+)$/gm)].map(m=>[m[1],Number(m[2])]));
  if(!counts.tests||counts.pass!==counts.tests||counts.fail||counts.cancelled||counts.skipped||counts.todo)throw Error('FULL_TEST_COVERAGE_REQUIRED');
  const inherited=JSON.parse(await readFile('contracts/inherited-invariants.json','utf8'));for(const name of inherited.inherited_test_names)if(!tests.stdout.includes('# Subtest: '+name+'\n'))throw Error('INHERITED_INVARIANT_TEST_MISSING:'+name);
  const demonstration=run(process.execPath,['scripts/demonstrate.mjs',E+'/demonstration']);await writeFile(E+'/demonstration-run.json',demonstration.stdout);await writeFile(E+'/demonstration-stderr.txt',demonstration.stderr);
  const execution=JSON.parse(await readFile(E+'/demonstration/execution-record.json','utf8'));
  const schema=run('python3',['scripts/check-schemas.py','schemas/submission.schema.json',E+'/demonstration/TEST-submission.json','schemas/result.schema.json',E+'/demonstration/TEST-standing-mark.json']);await writeFile(E+'/schemas.txt',schema.stdout);
  const refused=spawnSync('python3',['verify/verify_mark.py',E+'/demonstration/TEST-standing-mark.json','--root-pin',execution.root_pin],{encoding:'utf8',timeout:30000});if(refused.status!==1||!refused.stdout.includes('TEST_ARTIFACT_NOT_LIVE'))throw Error('TEST_MARK_WAS_NOT_REFUSED_AS_LIVE');await writeFile(E+'/test-not-live-refusal.json',refused.stdout);
  const cold=JSON.parse(await readFile(E+'/cold/report.json','utf8'));if(!cold.verified||cold['PROPAGATION-PROVEN']!=='TEST'||JSON.stringify(cold.tests)!=='["A","B","C"]'||cold.next_payment_authorizations!==0)throw Error('COLD_PROPAGATION_NOT_PROVEN');
  const after=await sourceManifest();if(before.sha256!==after.sha256)throw Error('TESTED_SOURCE_MUTATED_DURING_VERIFICATION');
  const report={build:'WHP Standing first public v1',version:'1.0.0',started_at:started,completed_at:new Date().toISOString(),node:process.version,python:run('python3',['--version']).stdout.trim(),python_packages:JSON.parse(run('python3',['-c','import importlib.metadata,json;print(json.dumps({k:importlib.metadata.version(k) for k in ["cryptography","jsonschema"]}))']).stdout),source_manifest_sha256:before.sha256,source_unchanged_during_proof:true,contract_commitments:JSON.parse(frozen.stdout),javascript_syntax_files:js.length,python_syntax_files:py.length,test_counts:counts,inherited_invariant_tests_passed:inherited.inherited_test_names.length,schemas_validated:true,real_local_http_transaction_executed:true,separate_process_retrieval_executed:true,independent_python_verifier_executed:true,test_artifact_refused_as_live:true,cold_agent_test_environment:'TEST',cold_agent_report:cold,
    demonstration:{purchase_id:execution.purchase_id,mark_id:execution.mark_id,mark_sha256:execution.mark_sha256,root_pin:execution.root_pin,wallet_signing_calls:execution.signer_invocations,settlement_calls:execution.settlement_calls,simulated_transfers:execution.simulated_transfers},
    evidence_states:{DESIGNED:true,IMPLEMENTED_SOURCE_PRESENT:true,VERIFIED_SCOPE:'full unit/adversarial/schema/local HTTP/SQLite/independent replay/cold A-B-C',DEPLOYED:false,LIVE:false,SOLD:false,ISSUED:false,'PROPAGATION-PROVEN':'TEST'},
    postgresql_integration_tested:false,complete_thread_proof:false,production_credentials_used:false,production_database_accessed:false,production_deployment_performed:false,live_facilitator_integration_tested:false,live_completion:false,external_security_audit_performed:false,github:{run_id:process.env.GITHUB_RUN_ID??null,run_attempt:process.env.GITHUB_RUN_ATTEMPT??null,workflow_ref:process.env.GITHUB_WORKFLOW_REF??null,checkout_commit:process.env.GITHUB_SHA??null}};
  await writeFile(E+'/core-verification.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
}catch(error){await writeFile(E+'/failure.json',JSON.stringify({verified:false,started_at:started,failed_at:new Date().toISOString(),error:error.message,complete_thread_proof:false},null,2)+'\n');console.error(error.stack);process.exitCode=1;}
